version: '3.7'
services:
  web:
    build: .
    image: app-laravel
    container_name: app-laravel
    restart: always
    expose:
      - 80
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    
networks:
  frontend:
    name: app_network